code = open('app.py','r',encoding='utf-8').read()
code = code.replace('GEMINI_API_KEY', 'GROQ_API_KEY')
code = code.replace('GEMINI_API_URL', 'GROQ_API_URL')
code = code.replace('GEMINI_MODELS', 'GROQ_MODELS')
code = code.replace('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', 'https://api.groq.com/openai/v1/chat/completions')
code = code.replace('gemini-2.0-flash-lite', 'llama-3.1-8b-instant')
code = code.replace('gemini-2.0-flash', 'llama-3.3-70b-versatile')
open('app.py','w',encoding='utf-8').write(code)
print('done')
